const gamepadButtons = [
  {
    keywords: ["Xbox"],
    buttons: {
      bt0: "A",
      bt1: "B",
      bt2: "X",
      bt3: "Y",
      bt4: "LB",
      bt5: "RB",
      bt6: "LT",
      bt7: "RT",
      bt8: "Back",
      bt9: "Start",
      bt10: "LS",
      bt11: "RS",
      bt12: "Up",
      bt13: "Down",
      bt14: "Left",
      bt15: "Right",
      ax0: "Left Stick X Axis",
      ax1: "Left Stick Y Axis",
      ax2: "Right Stick X Axis",
      ax3: "Right Stick Y Axis",
    },
  },
  {
    keywords: ["PlayStation"],
    buttons: {
      bt0: "Cross",
      bt1: "Circle",
      bt2: "Square",
      bt3: "Triangle",
      bt4: "L1",
      bt5: "R1",
      bt6: "L2",
      bt7: "R2",
      bt8: "Share",
      bt9: "Options",
      bt10: "L3",
      bt11: "R3",
      bt12: "Up",
      bt13: "Down",
      bt14: "Left",
      bt15: "Right",
      ax0: "Left Stick X Axis",
      ax1: "Left Stick Y Axis",
      ax2: "Right Stick X Axis",
      ax3: "Right Stick Y Axis",
    },
  },
];
